language: php

php:
- 7.1
- 7.2
- nightly

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install

script:
- composer run lint
- composer run test
